# Generated by Django 4.1.7 on 2023-06-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0002_autor_editora_livro"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="autores",
            field=models.ManyToManyField(related_name="livros", to="livraria.autor"),
        ),
    ]
